"""create tables for location domain

Revision ID: 034969b74154
Revises: 
Create Date: 2023-10-31 00:25:30.833633

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '034969b74154'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
                    sa.Column('name_en', sa.String(), nullable=False),
                    sa.Column('name_ar', sa.String(), nullable=False),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk__countries'))
                    )
    op.create_table('governorates',
                    sa.Column('name_en', sa.String(), nullable=False),
                    sa.Column('name_ar', sa.String(), nullable=False),
                    sa.Column('country_id', sa.Integer(), nullable=False),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['country_id'], ['countries.id'],
                                            name=op.f('fk__governorates__country_id__countries'), ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk__governorates'))
                    )
    op.create_index(op.f('ix__governorates__country_id'), 'governorates', ['country_id'], unique=False)
    op.create_table('cities',
                    sa.Column('name_en', sa.String(), nullable=False),
                    sa.Column('name_ar', sa.String(), nullable=False),
                    sa.Column('governorate_id', sa.Integer(), nullable=False),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['governorate_id'], ['governorates.id'],
                                            name=op.f('fk__cities__governorate_id__governorates'), ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk__cities'))
                    )
    op.create_index(op.f('ix__cities__governorate_id'), 'cities', ['governorate_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix__cities__governorate_id'), table_name='cities')
    op.drop_table('cities')
    op.drop_index(op.f('ix__governorates__country_id'), table_name='governorates')
    op.drop_table('governorates')
    op.drop_table('countries')
    # ### end Alembic commands ###
