"""fill egypt location data

Revision ID: 16dc813b54bb
Revises: 1dad8acbd02f
Create Date: 2023-11-04 14:30:39.229968

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from config import settings

# revision identifiers, used by Alembic.
revision: str = "16dc813b54bb"
down_revision: Union[str, None] = "1dad8acbd02f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sql_file = settings.root_dir / "data/egypt_location_data.sql"

    # Read the SQL file and split it into individual statements
    with open(sql_file, 'r') as f:
        sql_contents = f.read()
        sql_statements = sql_contents.split(';')

    # Execute each SQL statement
    conn = op.get_bind()
    for statement in sql_statements:
        if statement.strip():  # Skip empty statements
            conn.execute(sa.text(statement))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # split it into individual statements
    sql = "DELETE FROM cities; DELETE FROM governorates; DELETE FROM countries;"
    sql_statements = sql.split(';')

    # Execute each SQL statement
    conn = op.get_bind()
    for statement in sql_statements:
        if statement.strip():  # Skip empty statements
            conn.execute(sa.text(statement))
    # ### end Alembic commands ###
