"""update delete method on location tables

Revision ID: 1dad8acbd02f
Revises: 65c3a448903d
Create Date: 2023-11-04 01:21:47.437565

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '1dad8acbd02f'
down_revision: Union[str, None] = '65c3a448903d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk__cities__governorate_id__governorates', 'cities', type_='foreignkey')
    op.create_foreign_key(op.f('fk__cities__governorate_id__governorates'), 'cities', 'governorates', ['governorate_id'], ['id'], ondelete='RESTRICT')
    op.drop_constraint('fk__governorates__country_id__countries', 'governorates', type_='foreignkey')
    op.create_foreign_key(op.f('fk__governorates__country_id__countries'), 'governorates', 'countries', ['country_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk__governorates__country_id__countries'), 'governorates', type_='foreignkey')
    op.create_foreign_key('fk__governorates__country_id__countries', 'governorates', 'countries', ['country_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk__cities__governorate_id__governorates'), 'cities', type_='foreignkey')
    op.create_foreign_key('fk__cities__governorate_id__governorates', 'cities', 'governorates', ['governorate_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
